class Word {
  constructor(word, translate, number) {
    this.word = word;
    this.translate = translate;
    this.number = number;
  }
}

const WORDS = [
  new Word("Nurse", "Բույժքույր", 2),
  new Word("Interapting", "Ընդհատել", 2),
  new Word("Going to", "Պատրաստվել", 2),
  new Word("Spelling", "Ուղղագրություն", 2),
  new Word("Get to", "Հասնել", 2),
  new Word("Reach", "Հասնել", 2),
  new Word("Look to", "Փնտրել", 2),
  new Word("Things", "Առարկա", 2),
  new Word("Heavy", "Ծանր", 1),
  new Word("ill", "Հիվանդ", 1),
  new Word("Warm", "Տաք", 1),
  new Word("Coat", "Պալտո", 1),
  new Word("Windy", "Քամոտ", 1),
  new Word("Cheap", "Էժան", 1),
  new Word("Tired", "Հոգնած", 1),
  new Word("Lawyer", "Փաստաբան", 1),
  new Word("Typist", "Մեքենայագրող", 1),
  new Word("Shelf", "Դարակ", 1),
  new Word("Subject", "Իր", 1),
  new Word("Afraid", "Վախեցած", 1),
  new Word("Upset", "Նեղվել", 1),
  new Word("Kind", "Բարի", 1),
  new Word("Meal", "Ուտելիք", 1),
  new Word("Exciting", "Հուզված", 1),
  new Word("Debt", "Պարտք", 1),
  new Word("Worst", "Վատագույն", 1),
  new Word("Poverty", "Աղքատություն", 1),
  new Word("Worth", "Առժեք", 1),
  new Word("Reliable", "Հուսալիություն", 1),
  new Word("Forecast", "Կանծատեսում", 1),
  new Word("Expensive", "Թանկ", 1),
  new Word("Terrible", "Սարսափելի", 1),
  new Word("Sick", "Հիվանդ", 1),
  new Word("Yard", "Տարածք", 1),
  new Word("Living room", "Հյուրասենյակ", 1),
  new Word("Noisy", "Աղմուկ", 1),
  new Word("Sink", "Լվացարան", 1),
  new Word("Exhausted", "Տանջված", 1),
  new Word("Exhibition", "Ցուցահանդես", 1),
  new Word("Trip", "Ուղևորություն", 1),
  new Word("Excited", "Անհանգիստ", 1),
  new Word("Arrive", "Ժամանել", 1),
  new Word("Clever", "Խելացի", 1),
  new Word("Cruel", "Դաժան", 1),
  new Word("Lot", "Շատ", 1),
  new Word("Pleased", "Գոհ", 1),
  new Word("Safe", "Անվտանք", 1),
  new Word("Trick", "Հնարք", 1),
  new Word("Fear", "Վախ", 1),
  new Word("Loudly", "Բարձր", 1),
  new Word("Corner", "Անկյուն", 1),
  new Word("Thought", "Միտք", 1),
  new Word("Let", "Թույլ տալ", 1),
  new Word("Long ago", "Շատ շուտ", 1),
  new Word("Maple", "Կլյոն", 1),
  new Word("Sure", "Իհարկե", 1),
  new Word("Belt", "Գոտի", 1),
  new Word("Fool", "Խաբել", 1),
  new Word("Couple", "Զույգ", 1),
  new Word("Quite(well)", "Բավականին(լավ)", 1),
  new Word("Definition", "Համապատասխան", 1),
  new Word("Mad", "Խելագար", 1),
  new Word("Noon", "Կեսօր", 1),
  new Word("Cage", "Վանդակ", 1),
];

export default WORDS;
