class Word {
  constructor(word, translate) {
    this.word = word;
    this.translate = translate;
  }
}

const WORDS = [
  new Word("Heavy", "Ծանր"),
  new Word("Ill", "Հիվանդ"),
  new Word("Warm", "Տաք"),
  new Word("Coat", "Պալտո"),
  new Word("Windy", "Քամոտ"),
  new Word("Cheap", "Էժան"),
  new Word("Tired", "Հոգնած"),
  new Word("Lawyer", "Փաստաբան"),
  new Word("Typist", "Վարորդ"),
  new Word("Shelf", "Դարակ"),
  new Word("Subject", "Իր"),
  new Word("Afraid", "Վախեցած"),
  new Word("Upset", "Նեղվել"),
  new Word("Kind", "Վարի"),
  new Word("Meal", "Ուտելիք"),
  new Word("Exciting", "Գրավիչ"),
  new Word("Debt", "Պարտք"),
  new Word("Worst", "Վատագույն"),
  new Word("Poverty", "Աղքատություն"),
  new Word("Worth", "Առժեք"),
  new Word("Reliable", "Հուսալիություն"),
  new Word("Forecast", "Կանծատեսում"),
  new Word("Expensive", "Թանկ"),
  new Word("Terrible", "Սարսափելի"),
  new Word("Sick", "Հիվանդ"),
  new Word("Yard", "Տարածք"),
  new Word("Living room", "Հյուրասենյակ"),
  new Word("Noisy", "Աղմուկ"),
  new Word("Sink", "Լվացարան"),
  new Word("Exhausted", "Տանջված"),
  new Word("Exhibition", "Ցուցահանդես"),
  new Word("Trip", "Ուղևորություն"),
  new Word("Excited", "Անհանգիստ"),
  new Word("Arrive", "Ժամանել"),
  new Word("Clever", "Խելացի"),
  new Word("Cruel", "Դաժան"),
  new Word("Lot", "Շատ"),
  new Word("Pleased", "Գոհ"),
  new Word("Safe", "Անվտանք"),
  new Word("Trick", "Հնարք"),
  new Word("Fear", "Վախ"),
  new Word("Loudly", "Բարձր"),
  new Word("Corner", "Անկյուն"),
  new Word("Thought", "Միտք"),
  new Word("Let", "Թույլ տալ"),
  new Word("Long ago", "Շատ շուտ"),
  new Word("Maple", "Կլյոն"),
  new Word("Sure", "Իհարկե"),
  new Word("Belt", "Գոտի"),
  new Word("Fool", "Խաբել"),
  new Word("Couple", "Զույգ"),
  new Word("Quite(well)", "Բավականին(լավ)"),
  new Word("Definition", "Համապատասխան"),
  new Word("Mad", "Խելագար"),
  new Word("Noon", "Կեսօր"),
  new Word("Cage", "Վանդակ"),
];

export default WORDS;
